FROM eclipse-temurin:17

LABEL mentainer="shauzab1995abbas@gmail.com"

WORKDIR /app

COPY target/ShauzabPresentFamily-0.0.1-SNAPSHOT.jar /app/ShauzabPresentFamily-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","ShauzabPresentFamily-0.0.1-SNAPSHOT.jar"]